# Generated by Django 4.1.3 on 2022-12-03 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0004_event_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date_debut',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='event',
            name='date_fin',
            field=models.DateField(auto_now=True),
        ),
    ]
