# Generated by Django 4.1.3 on 2022-12-03 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0005_event_date_debut_event_date_fin'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='prix',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
